#!/usr/bin/env node

/**
 * 🔍 Media Scanner
 * 
 * Scans the media folders and auto-generates data files.
 * Run after dropping files into any folder:
 * 
 *   npm run scan
 * 
 * Folders:
 *   public/assets/memories/  → Our Little Moments (images + videos)
 *   public/assets/spiral/    → Infinite Spiral (images only)
 *   public/assets/music/     → Music Player
 *   public/assets/videos/    → Video Section (main video)
 *   public/assets/welcome/   → Welcome Screen hero image
 */

import { readdirSync, writeFileSync } from "fs";
import { join, extname } from "path";

const PUBLIC = "public";
const DATA = "src/data";

const IMAGE_EXTS = [".jpg", ".jpeg", ".png", ".webp", ".gif", ".bmp", ".svg"];
const VIDEO_EXTS = [".mp4", ".mov", ".webm", ".avi", ".mkv"];
const AUDIO_EXTS = [".mp3", ".wav", ".m4a", ".ogg", ".aac", ".flac"];

function scanDir(dir) {
  try {
    return readdirSync(join(PUBLIC, dir))
      .filter((f) => !f.startsWith("."))
      .sort();
  } catch {
    return [];
  }
}

function isImage(file) {
  return IMAGE_EXTS.includes(extname(file).toLowerCase());
}

function isVideo(file) {
  return VIDEO_EXTS.includes(extname(file).toLowerCase());
}

function isAudio(file) {
  return AUDIO_EXTS.includes(extname(file).toLowerCase());
}

// Clean filename into a readable caption
function toCaption(file) {
  return file
    .replace(/\.[^.]+$/, "")           // remove extension
    .replace(/[-_]/g, " ")             // dashes/underscores to spaces
    .replace(/([a-z])([A-Z])/g, "$1 $2") // camelCase split
    .replace(/\s+/g, " ")
    .trim();
}

// Clean filename into a song title
function toTitle(file) {
  const name = toCaption(file);
  // Try to split "Artist - Title" pattern
  const parts = name.split(" - ");
  if (parts.length >= 2) {
    return { artist: parts[0].trim(), title: parts.slice(1).join(" - ").trim() };
  }
  return { artist: "Unknown Artist", title: name };
}

// ── Scan Memories ─────────────────────────────
const memoryFiles = scanDir("assets/memories");
const memoryEntries = memoryFiles
  .filter((f) => isImage(f) || isVideo(f))
  .map((f) => {
    const type = isVideo(f) ? "video" : "image";
    return `  {\n    type: "${type}",\n    src: "/assets/memories/${f}",\n    caption: "${toCaption(f)} ❤️",\n  }`;
  });

const memoriesJS = `// Auto-generated by scan.js — run \`npm run scan\` after adding files
// Folder: public/assets/memories/

const memories = [
${memoryEntries.join(",\n")}
];

export default memories;
`;

writeFileSync(join(DATA, "memories.js"), memoriesJS);
console.log(`📸 Memories: ${memoryEntries.length} items found`);

// ── Scan Spiral ───────────────────────────────
const spiralFiles = scanDir("assets/spiral");
const spiralEntries = spiralFiles
  .filter(isImage)
  .map((f) => `  {\n    src: "/assets/spiral/${f}",\n    alt: "${toCaption(f)}",\n  }`);

const spiralJS = `// Auto-generated by scan.js — run \`npm run scan\` after adding files
// Folder: public/assets/spiral/

const spiralImages = [
${spiralEntries.join(",\n")}
];

export default spiralImages;
`;

writeFileSync(join(DATA, "spiralImages.js"), spiralJS);
console.log(`💫 Spiral: ${spiralEntries.length} images found`);

// ── Scan Music ────────────────────────────────
const musicFiles = scanDir("assets/music");
const musicEntries = musicFiles
  .filter(isAudio)
  .map((f) => {
    const { artist, title } = toTitle(f);
    return `  {\n    title: "${title}",\n    artist: "${artist}",\n    src: "/assets/music/${f}",\n  }`;
  });

const playlistJS = `// Auto-generated by scan.js — run \`npm run scan\` after adding files
// Folder: public/assets/music/

const playlist = [
${musicEntries.join(",\n")}
];

export default playlist;
`;

writeFileSync(join(DATA, "playlist.js"), playlistJS);
console.log(`🎵 Playlist: ${musicEntries.length} songs found`);

console.log("\n✅ All done! Data files updated.");
